CREATE TABLE user (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(200) NOT NULL,
  email VARCHAR(250) NOT NULL UNIQUE,
  cpf VARCHAR(14) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL
);